### ISSUE TITLE
How can I get signed pdf offline

### ISSUE THREAD

**Issue by Monika-Tapadiya** [docusign/sample-app-tgk-financial-ios#1]
Hello,

I am using Docusign SDK, I created one envelope with sign tab and able to draw sign in iOS offline but how can I retrieve that signed pdf just after confirm signing action button is pressed without calling any API?

Thanks

**Comment by ashokds** [comment]
Hi @Monika-Tapadiya ,

Offline signed PDF can't be retrieved just after signing. The document must be synced with the DocuSign server first and later on downloaded via API call. 

For offline envelopes, client apps may retrieve the PDF without signature and other tabs to preview it. Do you need such functionality?

Thanks.
